background = 0xFF000000
base = 0xFF162035
text = 0xFFd4e8f0
alternate_base = 0xFF1f2a3d
bright_text = 0xFFcceaff
accent = 0xFF00BCD4
accent_secondary = 0xFF00CED1
h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10
icon_theme = 
font_family = Sans Serif
font_family_monospace = monospace
rounding_large = 10
rounding_small = 5
