# Remember for fit_mode there is {contain,cover,tile,fill}
# path contains the path to the wallpapers files
wallpaper {
	monitor = 
	path = ~/Pictures/Wallpapers/retro-truck.png
	fit_mode = cover 
}

